[package]
name = "toyc"
version = "0.1.0"
authors = ["tarberd <bernardo.mferrari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toy-parser = { path = "../toy-parser" }
llvm-sys = "90.0.0"
