[package]
name = "toy-parser"
version = "0.1.0"
authors = ["tarberd <bernardo.mferrari@gmail.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.18.1"
regex = "1.3.5"

[build-dependencies]
lalrpop = { version = "0.18.1", features = ["lexer"] }
